CREATE TABLE IF NOT EXISTS `user_types` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '識別番号',
  `name` VARCHAR(50) NOT NULL COMMENT 'ユーザータイプ名',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '登録日時',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COMMENT="ユーザータイプ";
