CREATE TABLE IF NOT EXISTS `user_types` (
  `id` TINYINT NOT NULL AUTO_INCREMENT COMMENT '識別番号',
  `name` VARCHAR(50) NOT NULL COMMENT 'ユーザータイプ名',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '登録日時',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT="ユーザータイプ";
