run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - cyclop
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errorlint
    - exhaustive
    - exportloopref
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gocognit
    - goconst
    - gocyclo
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nestif
    - noctx
    - nolintlint
    - prealloc
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - wsl

linters-settings:
  funlen:
    lines: -1
  lll:
    line-length: 300
  whitespace:
    multi-if: true
    multi-func: true

issues:
  exclude-rules:
    - linters:
        - revive
      text: "exported:"
    - linters:
        - revive
      text: "unexported-return:"
    - linters:
        - revive
      text: "package-comments: should have a package comment"
    - linters:
        - stylecheck
      text: "ST1000:"
    - path: internal/utils/errorutil/error.go
      text: "mnd:"
      linters:
        - gomnd
    - path: internal/infra/s3/mock_s3_repository.go
      text: "var-naming:"
      linters:
        - revive
    - path: internal/infra/s3/mock_s3_repository.go
      text: "ST1003:"
      linters:
        - stylecheck
    - path: internal/infra/dynamodb/dynamodb_repository_test.go
      text: "ST1019"
      linters:
        - stylecheck
    - path: _handler\.go
      linters:
        - revive
    - path: _test\.go
      linters:
        - dupl
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
