version: "3.9"
services:
  app:
    image: example_echo
    build:
      context: .
      dockerfile: Dockerfile
      target: developer
    container_name: example_echo
    depends_on:
      - db
    env_file:
      - env/.env
    hostname: example_echo
    ports:
      - 3000:3000
    tty: true
    volumes:
      - .:/app/example_echo
    working_dir: /app/example_echo

  db:
    image: mysql:8.3.0@sha256:9de9d54fecee6253130e65154b930978b1fcc336bcc86dfd06e89b72a2588ebe
    container_name: twitter_db
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: twitter
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    platform: linux/x86_64
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ./db/mysql/data:/var/lib/mysql
