version: "3.9"
services:
  app:
    image: example_echo
    build:
      context: .
      dockerfile: Dockerfile
      target: developer
    container_name: example_echo
    depends_on:
      - db
    env_file:
      - env/.env
    hostname: example_echo
    ports:
      - 3000:3000
    tty: true
    volumes:
      - .:/app/example_echo
    working_dir: /app/example_echo

  db:
    image: mysql:8.4.1@sha256:a7dc4a4e07a9c5d53c0cf36b5b4e8a1b3bb677cb0d544256a0581114a93ddf0f
    container_name: twitter_db
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: twitter
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    platform: linux/x86_64
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ./db/mysql/data:/var/lib/mysql
