version: "3.9"
services:
  app:
    image: example_echo
    build:
      context: .
      dockerfile: Dockerfile
      target: developer
    container_name: example_echo
    depends_on:
      - db
    env_file:
      - env/.env
    hostname: example_echo
    ports:
      - 3000:3000
    tty: true
    volumes:
      - .:/app/example_echo
    working_dir: /app/example_echo

  db:
    image: mysql:9.1.0@sha256:2be51594eba5983f47e67ff5cb87d666a223e309c6c64450f30b5c59a788ea40
    container_name: twitter_db
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: twitter
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    platform: linux/x86_64
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ./db/mysql/data:/var/lib/mysql
