version: "3.9"
services:
  app:
    image: example_echo
    build:
      context: .
      dockerfile: Dockerfile
      target: developer
    container_name: example_echo
    depends_on:
      - db
    env_file:
      - env/.env
    hostname: example_echo
    ports:
      - 3000:3000
    tty: true
    volumes:
      - .:/app/example_echo
    working_dir: /app/example_echo

  db:
    image: mysql:8.2.0@sha256:1773f3c7aa9522f0014d0ad2bbdaf597ea3b1643c64c8ccc2123c64afd8b82b1
    container_name: twitter_db
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: twitter
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    platform: linux/x86_64
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ./db/mysql/data:/var/lib/mysql
