version: "3.9"
services:
  app:
    image: example_echo
    build:
      context: .
      dockerfile: Dockerfile
      target: developer
    container_name: example_echo
    depends_on:
      - db
    env_file:
      - env/.env
    hostname: example_echo
    ports:
      - 3000:3000
    tty: true
    volumes:
      - .:/app/example_echo
    working_dir: /app/example_echo

  db:
    image: mysql:8.4.2@sha256:a55b5347ff7d7e8e644e39dd7bc0d747834c254921010eeb5a90691987a12022
    container_name: twitter_db
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: twitter
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    platform: linux/x86_64
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ./db/mysql/data:/var/lib/mysql
