version: "3.9"
services:
  app:
    image: example_serverless_go
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    container_name: example_serverless_go
    env_file:
      - Docker/local.env
    hostname: example_serverless_go
    tty: true
    volumes:
      - .:/home/tempUser/example_serverless_go
    working_dir: /home/tempUser/example_serverless_go

  db:
    image: genschsa/mysql-employees
    container_name: mysql-employees
    environment:
      MYSQL_ROOT_PASSWORD: college
    platform: linux/x86_64
    ports:
      - 127.0.0.1:3306:3306
    restart: always
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
