version: "3.9"
services:
  app:
    image: example_serverless_go
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    container_name: example_serverless_go
    hostname: example_serverless_go
    tty: true
    volumes:
      - .:/home/tempUser/example_serverless_go
    working_dir: /home/tempUser/example_serverless_go
