pkgname = "model"
output = "internal/domain/model"
add-enum-types = true
no-tests = true
wipe = true

[mysql]
  dbname     = "employees"
  host       = "db"
  port       = 3306
  user       = "root"
  pass       = "college"
  sslmode    = "false"
