// Code generated by SQLBoiler 4.14.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package boiler

var ViewNames = struct {
	CurrentDeptEmp    string
	DeptEmpLatestDate string
	VFullDepartments  string
	VFullEmployees    string
}{
	CurrentDeptEmp:    "current_dept_emp",
	DeptEmpLatestDate: "dept_emp_latest_date",
	VFullDepartments:  "v_full_departments",
	VFullEmployees:    "v_full_employees",
}
