pkgname = "model"
output = "internal/domain/model"
add-enum-types = true
no-tests = true
wipe = true

[mysql]
  dbname     = "twitter"
  host       = "db"
  port       = 3306
  user       = "user"
  pass       = "password"
  sslmode    = "false"
  blacklist = ["schema_migrations"]
