// Code generated by SQLBoiler 4.14.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// DeptManager is an object representing the database table.
type DeptManager struct {
	EmpNo    int       `boil:"emp_no" json:"emp_no" toml:"emp_no" yaml:"emp_no"`
	DeptNo   string    `boil:"dept_no" json:"dept_no" toml:"dept_no" yaml:"dept_no"`
	FromDate time.Time `boil:"from_date" json:"from_date" toml:"from_date" yaml:"from_date"`
	ToDate   time.Time `boil:"to_date" json:"to_date" toml:"to_date" yaml:"to_date"`

	R *deptManagerR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L deptManagerL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var DeptManagerColumns = struct {
	EmpNo    string
	DeptNo   string
	FromDate string
	ToDate   string
}{
	EmpNo:    "emp_no",
	DeptNo:   "dept_no",
	FromDate: "from_date",
	ToDate:   "to_date",
}

var DeptManagerTableColumns = struct {
	EmpNo    string
	DeptNo   string
	FromDate string
	ToDate   string
}{
	EmpNo:    "dept_manager.emp_no",
	DeptNo:   "dept_manager.dept_no",
	FromDate: "dept_manager.from_date",
	ToDate:   "dept_manager.to_date",
}

// Generated where

var DeptManagerWhere = struct {
	EmpNo    whereHelperint
	DeptNo   whereHelperstring
	FromDate whereHelpertime_Time
	ToDate   whereHelpertime_Time
}{
	EmpNo:    whereHelperint{field: "`dept_manager`.`emp_no`"},
	DeptNo:   whereHelperstring{field: "`dept_manager`.`dept_no`"},
	FromDate: whereHelpertime_Time{field: "`dept_manager`.`from_date`"},
	ToDate:   whereHelpertime_Time{field: "`dept_manager`.`to_date`"},
}

// DeptManagerRels is where relationship names are stored.
var DeptManagerRels = struct {
	EmpNoEmployee    string
	DeptNoDepartment string
}{
	EmpNoEmployee:    "EmpNoEmployee",
	DeptNoDepartment: "DeptNoDepartment",
}

// deptManagerR is where relationships are stored.
type deptManagerR struct {
	EmpNoEmployee    *Employee   `boil:"EmpNoEmployee" json:"EmpNoEmployee" toml:"EmpNoEmployee" yaml:"EmpNoEmployee"`
	DeptNoDepartment *Department `boil:"DeptNoDepartment" json:"DeptNoDepartment" toml:"DeptNoDepartment" yaml:"DeptNoDepartment"`
}

// NewStruct creates a new relationship struct
func (*deptManagerR) NewStruct() *deptManagerR {
	return &deptManagerR{}
}

func (r *deptManagerR) GetEmpNoEmployee() *Employee {
	if r == nil {
		return nil
	}
	return r.EmpNoEmployee
}

func (r *deptManagerR) GetDeptNoDepartment() *Department {
	if r == nil {
		return nil
	}
	return r.DeptNoDepartment
}

// deptManagerL is where Load methods for each relationship are stored.
type deptManagerL struct{}

var (
	deptManagerAllColumns            = []string{"emp_no", "dept_no", "from_date", "to_date"}
	deptManagerColumnsWithoutDefault = []string{"emp_no", "dept_no", "from_date", "to_date"}
	deptManagerColumnsWithDefault    = []string{}
	deptManagerPrimaryKeyColumns     = []string{"emp_no", "dept_no"}
	deptManagerGeneratedColumns      = []string{}
)

type (
	// DeptManagerSlice is an alias for a slice of pointers to DeptManager.
	// This should almost always be used instead of []DeptManager.
	DeptManagerSlice []*DeptManager
	// DeptManagerHook is the signature for custom DeptManager hook methods
	DeptManagerHook func(context.Context, boil.ContextExecutor, *DeptManager) error

	deptManagerQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	deptManagerType                 = reflect.TypeOf(&DeptManager{})
	deptManagerMapping              = queries.MakeStructMapping(deptManagerType)
	deptManagerPrimaryKeyMapping, _ = queries.BindMapping(deptManagerType, deptManagerMapping, deptManagerPrimaryKeyColumns)
	deptManagerInsertCacheMut       sync.RWMutex
	deptManagerInsertCache          = make(map[string]insertCache)
	deptManagerUpdateCacheMut       sync.RWMutex
	deptManagerUpdateCache          = make(map[string]updateCache)
	deptManagerUpsertCacheMut       sync.RWMutex
	deptManagerUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var deptManagerAfterSelectHooks []DeptManagerHook

var deptManagerBeforeInsertHooks []DeptManagerHook
var deptManagerAfterInsertHooks []DeptManagerHook

var deptManagerBeforeUpdateHooks []DeptManagerHook
var deptManagerAfterUpdateHooks []DeptManagerHook

var deptManagerBeforeDeleteHooks []DeptManagerHook
var deptManagerAfterDeleteHooks []DeptManagerHook

var deptManagerBeforeUpsertHooks []DeptManagerHook
var deptManagerAfterUpsertHooks []DeptManagerHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *DeptManager) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range deptManagerAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *DeptManager) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range deptManagerBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *DeptManager) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range deptManagerAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *DeptManager) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range deptManagerBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *DeptManager) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range deptManagerAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *DeptManager) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range deptManagerBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *DeptManager) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range deptManagerAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *DeptManager) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range deptManagerBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *DeptManager) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range deptManagerAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddDeptManagerHook registers your hook function for all future operations.
func AddDeptManagerHook(hookPoint boil.HookPoint, deptManagerHook DeptManagerHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		deptManagerAfterSelectHooks = append(deptManagerAfterSelectHooks, deptManagerHook)
	case boil.BeforeInsertHook:
		deptManagerBeforeInsertHooks = append(deptManagerBeforeInsertHooks, deptManagerHook)
	case boil.AfterInsertHook:
		deptManagerAfterInsertHooks = append(deptManagerAfterInsertHooks, deptManagerHook)
	case boil.BeforeUpdateHook:
		deptManagerBeforeUpdateHooks = append(deptManagerBeforeUpdateHooks, deptManagerHook)
	case boil.AfterUpdateHook:
		deptManagerAfterUpdateHooks = append(deptManagerAfterUpdateHooks, deptManagerHook)
	case boil.BeforeDeleteHook:
		deptManagerBeforeDeleteHooks = append(deptManagerBeforeDeleteHooks, deptManagerHook)
	case boil.AfterDeleteHook:
		deptManagerAfterDeleteHooks = append(deptManagerAfterDeleteHooks, deptManagerHook)
	case boil.BeforeUpsertHook:
		deptManagerBeforeUpsertHooks = append(deptManagerBeforeUpsertHooks, deptManagerHook)
	case boil.AfterUpsertHook:
		deptManagerAfterUpsertHooks = append(deptManagerAfterUpsertHooks, deptManagerHook)
	}
}

// One returns a single deptManager record from the query.
func (q deptManagerQuery) One(ctx context.Context, exec boil.ContextExecutor) (*DeptManager, error) {
	o := &DeptManager{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "model: failed to execute a one query for dept_manager")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all DeptManager records from the query.
func (q deptManagerQuery) All(ctx context.Context, exec boil.ContextExecutor) (DeptManagerSlice, error) {
	var o []*DeptManager

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "model: failed to assign all query results to DeptManager slice")
	}

	if len(deptManagerAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all DeptManager records in the query.
func (q deptManagerQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "model: failed to count dept_manager rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q deptManagerQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "model: failed to check if dept_manager exists")
	}

	return count > 0, nil
}

// EmpNoEmployee pointed to by the foreign key.
func (o *DeptManager) EmpNoEmployee(mods ...qm.QueryMod) employeeQuery {
	queryMods := []qm.QueryMod{
		qm.Where("`emp_no` = ?", o.EmpNo),
	}

	queryMods = append(queryMods, mods...)

	return Employees(queryMods...)
}

// DeptNoDepartment pointed to by the foreign key.
func (o *DeptManager) DeptNoDepartment(mods ...qm.QueryMod) departmentQuery {
	queryMods := []qm.QueryMod{
		qm.Where("`dept_no` = ?", o.DeptNo),
	}

	queryMods = append(queryMods, mods...)

	return Departments(queryMods...)
}

// LoadEmpNoEmployee allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (deptManagerL) LoadEmpNoEmployee(ctx context.Context, e boil.ContextExecutor, singular bool, maybeDeptManager interface{}, mods queries.Applicator) error {
	var slice []*DeptManager
	var object *DeptManager

	if singular {
		var ok bool
		object, ok = maybeDeptManager.(*DeptManager)
		if !ok {
			object = new(DeptManager)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeDeptManager)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeDeptManager))
			}
		}
	} else {
		s, ok := maybeDeptManager.(*[]*DeptManager)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeDeptManager)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeDeptManager))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &deptManagerR{}
		}
		args = append(args, object.EmpNo)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &deptManagerR{}
			}

			for _, a := range args {
				if a == obj.EmpNo {
					continue Outer
				}
			}

			args = append(args, obj.EmpNo)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`employees`),
		qm.WhereIn(`employees.emp_no in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Employee")
	}

	var resultSlice []*Employee
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Employee")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for employees")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for employees")
	}

	if len(employeeAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.EmpNoEmployee = foreign
		if foreign.R == nil {
			foreign.R = &employeeR{}
		}
		foreign.R.EmpNoDeptManagers = append(foreign.R.EmpNoDeptManagers, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.EmpNo == foreign.EmpNo {
				local.R.EmpNoEmployee = foreign
				if foreign.R == nil {
					foreign.R = &employeeR{}
				}
				foreign.R.EmpNoDeptManagers = append(foreign.R.EmpNoDeptManagers, local)
				break
			}
		}
	}

	return nil
}

// LoadDeptNoDepartment allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (deptManagerL) LoadDeptNoDepartment(ctx context.Context, e boil.ContextExecutor, singular bool, maybeDeptManager interface{}, mods queries.Applicator) error {
	var slice []*DeptManager
	var object *DeptManager

	if singular {
		var ok bool
		object, ok = maybeDeptManager.(*DeptManager)
		if !ok {
			object = new(DeptManager)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeDeptManager)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeDeptManager))
			}
		}
	} else {
		s, ok := maybeDeptManager.(*[]*DeptManager)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeDeptManager)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeDeptManager))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &deptManagerR{}
		}
		args = append(args, object.DeptNo)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &deptManagerR{}
			}

			for _, a := range args {
				if a == obj.DeptNo {
					continue Outer
				}
			}

			args = append(args, obj.DeptNo)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`departments`),
		qm.WhereIn(`departments.dept_no in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Department")
	}

	var resultSlice []*Department
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Department")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for departments")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for departments")
	}

	if len(departmentAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.DeptNoDepartment = foreign
		if foreign.R == nil {
			foreign.R = &departmentR{}
		}
		foreign.R.DeptNoDeptManagers = append(foreign.R.DeptNoDeptManagers, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.DeptNo == foreign.DeptNo {
				local.R.DeptNoDepartment = foreign
				if foreign.R == nil {
					foreign.R = &departmentR{}
				}
				foreign.R.DeptNoDeptManagers = append(foreign.R.DeptNoDeptManagers, local)
				break
			}
		}
	}

	return nil
}

// SetEmpNoEmployee of the deptManager to the related item.
// Sets o.R.EmpNoEmployee to related.
// Adds o to related.R.EmpNoDeptManagers.
func (o *DeptManager) SetEmpNoEmployee(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Employee) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `dept_manager` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"emp_no"}),
		strmangle.WhereClause("`", "`", 0, deptManagerPrimaryKeyColumns),
	)
	values := []interface{}{related.EmpNo, o.EmpNo, o.DeptNo}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.EmpNo = related.EmpNo
	if o.R == nil {
		o.R = &deptManagerR{
			EmpNoEmployee: related,
		}
	} else {
		o.R.EmpNoEmployee = related
	}

	if related.R == nil {
		related.R = &employeeR{
			EmpNoDeptManagers: DeptManagerSlice{o},
		}
	} else {
		related.R.EmpNoDeptManagers = append(related.R.EmpNoDeptManagers, o)
	}

	return nil
}

// SetDeptNoDepartment of the deptManager to the related item.
// Sets o.R.DeptNoDepartment to related.
// Adds o to related.R.DeptNoDeptManagers.
func (o *DeptManager) SetDeptNoDepartment(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Department) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `dept_manager` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"dept_no"}),
		strmangle.WhereClause("`", "`", 0, deptManagerPrimaryKeyColumns),
	)
	values := []interface{}{related.DeptNo, o.EmpNo, o.DeptNo}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.DeptNo = related.DeptNo
	if o.R == nil {
		o.R = &deptManagerR{
			DeptNoDepartment: related,
		}
	} else {
		o.R.DeptNoDepartment = related
	}

	if related.R == nil {
		related.R = &departmentR{
			DeptNoDeptManagers: DeptManagerSlice{o},
		}
	} else {
		related.R.DeptNoDeptManagers = append(related.R.DeptNoDeptManagers, o)
	}

	return nil
}

// DeptManagers retrieves all the records using an executor.
func DeptManagers(mods ...qm.QueryMod) deptManagerQuery {
	mods = append(mods, qm.From("`dept_manager`"))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"`dept_manager`.*"})
	}

	return deptManagerQuery{q}
}

// FindDeptManager retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindDeptManager(ctx context.Context, exec boil.ContextExecutor, empNo int, deptNo string, selectCols ...string) (*DeptManager, error) {
	deptManagerObj := &DeptManager{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `dept_manager` where `emp_no`=? AND `dept_no`=?", sel,
	)

	q := queries.Raw(query, empNo, deptNo)

	err := q.Bind(ctx, exec, deptManagerObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "model: unable to select from dept_manager")
	}

	if err = deptManagerObj.doAfterSelectHooks(ctx, exec); err != nil {
		return deptManagerObj, err
	}

	return deptManagerObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *DeptManager) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("model: no dept_manager provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(deptManagerColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	deptManagerInsertCacheMut.RLock()
	cache, cached := deptManagerInsertCache[key]
	deptManagerInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			deptManagerAllColumns,
			deptManagerColumnsWithDefault,
			deptManagerColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(deptManagerType, deptManagerMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(deptManagerType, deptManagerMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `dept_manager` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `dept_manager` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `dept_manager` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, deptManagerPrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	_, err = exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "model: unable to insert into dept_manager")
	}

	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.EmpNo,
		o.DeptNo,
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, identifierCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "model: unable to populate default values for dept_manager")
	}

CacheNoHooks:
	if !cached {
		deptManagerInsertCacheMut.Lock()
		deptManagerInsertCache[key] = cache
		deptManagerInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the DeptManager.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *DeptManager) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	deptManagerUpdateCacheMut.RLock()
	cache, cached := deptManagerUpdateCache[key]
	deptManagerUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			deptManagerAllColumns,
			deptManagerPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("model: unable to update dept_manager, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `dept_manager` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, deptManagerPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(deptManagerType, deptManagerMapping, append(wl, deptManagerPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "model: unable to update dept_manager row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "model: failed to get rows affected by update for dept_manager")
	}

	if !cached {
		deptManagerUpdateCacheMut.Lock()
		deptManagerUpdateCache[key] = cache
		deptManagerUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q deptManagerQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "model: unable to update all for dept_manager")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "model: unable to retrieve rows affected for dept_manager")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o DeptManagerSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("model: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), deptManagerPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `dept_manager` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, deptManagerPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "model: unable to update all in deptManager slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "model: unable to retrieve rows affected all in update all deptManager")
	}
	return rowsAff, nil
}

var mySQLDeptManagerUniqueColumns = []string{}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *DeptManager) Upsert(ctx context.Context, exec boil.ContextExecutor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("model: no dept_manager provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(deptManagerColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLDeptManagerUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	deptManagerUpsertCacheMut.RLock()
	cache, cached := deptManagerUpsertCache[key]
	deptManagerUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			deptManagerAllColumns,
			deptManagerColumnsWithDefault,
			deptManagerColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			deptManagerAllColumns,
			deptManagerPrimaryKeyColumns,
		)

		if !updateColumns.IsNone() && len(update) == 0 {
			return errors.New("model: unable to upsert dept_manager, could not build update column list")
		}

		ret = strmangle.SetComplement(ret, nzUniques)
		cache.query = buildUpsertQueryMySQL(dialect, "`dept_manager`", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `dept_manager` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(deptManagerType, deptManagerMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(deptManagerType, deptManagerMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	_, err = exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "model: unable to upsert for dept_manager")
	}

	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(deptManagerType, deptManagerMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "model: unable to retrieve unique values for dept_manager")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, nzUniqueCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "model: unable to populate default values for dept_manager")
	}

CacheNoHooks:
	if !cached {
		deptManagerUpsertCacheMut.Lock()
		deptManagerUpsertCache[key] = cache
		deptManagerUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single DeptManager record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *DeptManager) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("model: no DeptManager provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), deptManagerPrimaryKeyMapping)
	sql := "DELETE FROM `dept_manager` WHERE `emp_no`=? AND `dept_no`=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "model: unable to delete from dept_manager")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "model: failed to get rows affected by delete for dept_manager")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q deptManagerQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("model: no deptManagerQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "model: unable to delete all from dept_manager")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "model: failed to get rows affected by deleteall for dept_manager")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o DeptManagerSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(deptManagerBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), deptManagerPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `dept_manager` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, deptManagerPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "model: unable to delete all from deptManager slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "model: failed to get rows affected by deleteall for dept_manager")
	}

	if len(deptManagerAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *DeptManager) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindDeptManager(ctx, exec, o.EmpNo, o.DeptNo)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *DeptManagerSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := DeptManagerSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), deptManagerPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `dept_manager`.* FROM `dept_manager` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, deptManagerPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "model: unable to reload all in DeptManagerSlice")
	}

	*o = slice

	return nil
}

// DeptManagerExists checks if the DeptManager row exists.
func DeptManagerExists(ctx context.Context, exec boil.ContextExecutor, empNo int, deptNo string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `dept_manager` where `emp_no`=? AND `dept_no`=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, empNo, deptNo)
	}
	row := exec.QueryRowContext(ctx, sql, empNo, deptNo)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "model: unable to check if dept_manager exists")
	}

	return exists, nil
}

// Exists checks if the DeptManager row exists.
func (o *DeptManager) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return DeptManagerExists(ctx, exec, o.EmpNo, o.DeptNo)
}
