run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bodyclose
    - containedctx
    - contextcheck
    - decorder
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - gochecknoglobals
    - gocognit
    - gofmt
    - gofumpt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - noctx
    - tagalign
    - unparam
    - unused
    - wsl

linters-settings:
  decorder:
    dec-order:
      - type
      - const
      - var
      - func
    disable-dec-order-check: false
    disable-init-func-first-check: false
    disable-dec-num-check: false
  errcheck:
    check-type-assertions: true
    check-blank: true
    disable-default-exclusions: false
    exclude-functions:
      - io/ioutil.ReadFile
      - io.Copy(*bytes.Buffer)
      - io.Copy(os.Stdout)
  errorlint:
    errorf: true
    errorf-multi: true
    asserts: true
    comparison: true
  exhaustive:
    check:
      - switch
      - map
    check-generated: false
    default-signifies-exhaustive: false
    package-scope-only: false
    explicit-exhaustive-switch: false
    explicit-exhaustive-map: false
  gocognit:
    min-complexity: 20
  gofmt:
    simplify: true
    rewrite-rules:
      - pattern: 'a[b:len(a)]'
        replacement: 'a[b:]'
  gofumpt:
    extra-rules: true
  gosec:
    exclude-generated: true
    severity: low
    confidence: low
  govet:
    check-shadowing: true
    enable-all: true
  lll:
    line-length: 140
  tagalign:
    align: true
    sort: true
    order:
      - json
      - yaml
      - yml
      - toml
      - mapstructure
      - binding
      - validate
  unparam:
    check-exported: false
  whitespace:
    multi-if: true
    multi-func: true

issues:
  exclude-rules:
    - path: internal/config/
      linters:
        - decorder
    - path: internal/domain/model/
      linters:
        - lll
        - unused
    - path: internal/infra/dynamodb/dynamodb_session.go
      linters:
        - decorder
    - path: internal/infra/mock/
      linters:
        - lll
        - unused
    - path: internal/infra/mysql/cluster.go
      linters:
        - decorder
    - path: _test\.go
      text: "fieldalignment"
      linters:
        - govet
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
