// Code generated by SQLBoiler 4.14.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package model

var TableNames = struct {
	AdminUsers string
	UserTypes  string
	Users      string
}{
	AdminUsers: "admin_users",
	UserTypes:  "user_types",
	Users:      "users",
}
