// Code generated by SQLBoiler 4.14.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package model

var TableNames = struct {
	Departments string
	DeptEmp     string
	DeptManager string
	Employees   string
	Salaries    string
	Titles      string
}{
	Departments: "departments",
	DeptEmp:     "dept_emp",
	DeptManager: "dept_manager",
	Employees:   "employees",
	Salaries:    "salaries",
	Titles:      "titles",
}
