name: CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5
        with:
          go-version-file: "go.mod"
          cache: true
      - name: Download go modules
        run: go mod download
      - name: Compile go packages
        run: go build -o example_echo cmd/main.go
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: reviewdog/action-golangci-lint@94d61e3205b61acf4ddabfeb13c5f8a13eb4167b # v2
        with:
          github_token: ${{ github.token }}
          go_version_file: "go.mod"
          golangci_lint_flags: "--config=config/.golangci.yml"
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 3
    needs:
      - build
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5
        with:
          go-version-file: "go.mod"
          cache: true
      - name: Run tests
        run: go test ./...
