name: Hadolint

on:
  pull_request:
    paths:
      - Dockerfile
  workflow_dispatch:

jobs:
  hadolint:
    name: Hadolint
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v3.0.0
        with:
          ignore: DL4006
