name: Hadolint

on:
  pull_request:
    paths:
      - Dockerfile
  workflow_dispatch:

jobs:
  hadolint:
    name: Hadolint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Run actions/checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Run hadolint/hadolint-action
        uses: hadolint/hadolint-action@54c9adbab1582c2ef04b2016b760714a4bfde3cf # v3.1.0
        with:
          ignore: DL3018,DL4006
