name: hadolint
on:
  pull_request:
    paths:
      - Dockerfile
jobs:
  timeout-minutes: 3
  hadolint:
    name: hadolint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: hadolint/hadolint-action@v3.0.0
        with:
          ignore: DL4006
