name: lint
on: [pull_request]
jobs:
  golangci-lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: reviewdog/action-golangci-lint@v2
        with:
          github_token: ${{ github.token }}
          go_version: "1.19"
          golangci_lint_flags: "--config=.golangci.yml"
          golangci_lint_version: "v1.50.1"
